id: A1DD3D06A
title: Visualization and Mantra Recitation of the Great Compassionate One
type: translation
pechas:
- I782560D3
- I20F98073
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2023-01-04 11:46:52.989092
  last_modified_at: 2023-01-04 11:46:52.989104
  collections:
  - Dudjom Lingpa Series
  - Works of Tibetan Masters
alignment_to_base:
  I782560D3/3AC9: C246
  I20F98073/9442: C246
